### ISSUE TITLE
Offer cartridge role

### ISSUE THREAD

**Issue by Totktonada** [tarantool/expirationd#107]
It'll easy setup periodical expiration in a cartridge application.

**Comment by oleg-jukovec** [comment]
We had a pull request before. It's a simple role for tests:
https://github.com/tarantool/expirationd/pull/67

The role is not an independent unit. It just saves the states of expirationd's tasks. Tasks must be started from the client code manually. 

So I propose an another approach:

1. Launching tasks from a configuration file.
2. Arguments for launching are similar as for [expirationd.start](https://tarantool.github.io/expirationd/#start) + the role parameters.
3. The role parameter can be: restart or try to restore from previous state? Something else?

```yaml
expirationd:
  first_role_name:
    space_id: "space_id"
    is_expired: "is_expired_func"
    options:
       args: "arg"
       force: true
       full_scan_delay: 1
       etc
    resume: true
  second_role_name:
    space_id: "space_id_second"
    is_expired: "is_expired_func_second"
    options:
       args: "arg"
       force: true
       full_scan_delay: 1
       etc
    resume: false
```

We can load functions by name from ```_G``` table:

```lua
local function load_function(func_name)
    if from == nil or type(func_name) ~= 'string' then
        return nil
    end

    local func = rawget(_G, func_name)
    if func == nil or type(func) ~= 'function' then
        return nil
    end
    return func
end
```

The role function ```stop``` will be very simple:

```lua
local function stop()
    for _, task in tasks_list do
        log.info('stop expirationd task: %s', task)
        expirationd.kill(task)
    end
    tasks_list = {}
    return true
end
```

```validate_config``` and ```apply_config``` will be much more complicated. We must to validate very many parameters in ```validate_config```. ```apply_config``` is a good place to start/realod tasks. Something like that:

```lua
local function apply_config(conf, opts) -- luacheck: no unused args
    local conf = conf[role_name] or {}

    stop()
    if opts.is_master then
        start(conf)
    end

    return true
end
```

**I have two questions:**
1. What additional parameters are needed for the role? Do we need to try to resume tasks, or is it enough just to start it? Do we need a parameter for this?
2. Do we need additional methods for configuration from a client code, as it is done, for example, in [metrics.lua](https://github.com/tarantool/metrics/blob/82bf601d766d6d1d02986c38c4136facd240ea9e/cartridge/roles/metrics.lua#L246)?

But I propose to start with a simple implementation. And add additional parameters/functions later.
