### ISSUE TITLE
Add ability to pass cfg options via cartridge role configuration

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/expirationd#131]
Metrics cannot be enabled via the cartridge role configuration. Now we still need to write the cartridge role code. It would be great to support the feature:

```yaml
expirationd:
  cfg:
    # expirationd.cfg() params
    metrics: true
  task_name_1:
    # the task configuration
  task_name_2:
    # the task configuration
```
