### ISSUE TITLE
Not able to use persistent functions

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/expirationd#153]
I want to be able to use functions created via box.func.create in expirationd cartridge role configuration. E.g.:

```yaml
expirationd:
  cfg:
    metrics: true
  task_name1:
    space: 579
    is_expired: box.func.my_custom_func
```

where function box.func.my_custom_func has been created via [box.func.create](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_schema/func_create/). 

This is not working now because function created via box.func.create are not exported to _G which breaks expirationd configuration (https://github.com/tarantool/expirationd/blob/master/cartridge/roles/expirationd.lua#L10) and leads to errors like this: ```expirationd: is_expired must be a function name in _G```.
